#!/usr/bin/env bash

rm -rf ~/.local/share/nvim
rm ~/.config/nvim
ln -s ~/Projects/nvim-unified ~/.config/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim

mkdir -p ~/.local/share/nvim/opt/phpactor/bin/
phpactor_path=$(which phpactor)
ln -s "${phpactor_path}"  ~/.local/share/nvim/opt/phpactor/bin/phpactor
nvim --headless "+Lazy! sync" +qa
